-- LUDIA NAIL · Naver SmartPlace bridge persistence
create table if not exists public.external_bookings (
  id bigint generated by default as identity primary key,
  source text not null check (source in ('NAVER')),
  external_id text not null,
  booking_no text,
  booking_date text,
  booking_time text,
  phone text,
  status text not null default 'unknown',
  raw_text text,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(source, external_id)
);

create table if not exists public.booking_sync_events (
  id bigint generated by default as identity primary key,
  event_type text not null check (event_type in ('created','updated')),
  source text not null check (source in ('NAVER')),
  external_id text not null,
  booking_no text,
  booking_date text,
  booking_time text,
  phone text,
  status text not null default 'unknown',
  raw_text text,
  received_at timestamptz not null default now()
);

create table if not exists public.integration_connections (
  id bigint generated by default as identity primary key,
  provider text not null unique,
  display_name text not null,
  state text not null default 'setup_required',
  last_sync_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists external_bookings_date_idx on public.external_bookings(booking_date, booking_time);
create index if not exists booking_sync_events_received_idx on public.booking_sync_events(received_at desc);

alter table public.external_bookings enable row level security;
alter table public.booking_sync_events enable row level security;
alter table public.integration_connections enable row level security;

-- The Vercel endpoint uses the service-role key and therefore bypasses RLS.
-- Do not expose SUPABASE_SERVICE_ROLE_KEY to the browser or the Windows bridge.
