-- LUDIA NAIL · Naver SmartPlace conflict guard
-- Apply after salon_os.sql, naver_bridge.sql and naver_booking_mapping.sql.
-- A Naver change must not silently move an already-assigned staff appointment on top of
-- another active appointment. Unassigned bookings are left to the existing projection
-- because LUDIA cannot safely guess a staff member.

create table if not exists public.ludia_naver_sync_conflicts (
  id bigint generated by default as identity primary key,
  salon_id uuid not null references public.ludia_salons(id) on delete cascade,
  appointment_id uuid not null references public.ludia_appointments(id) on delete cascade,
  conflicting_appointment_id uuid not null references public.ludia_appointments(id) on delete cascade,
  external_id text not null,
  requested_starts_at timestamptz not null,
  requested_ends_at timestamptz not null,
  detected_at timestamptz not null default now(),
  resolved_at timestamptz,
  resolution text check (resolution is null or resolution in ('kept_ludia','moved_ludia','accepted_naver')),
  check (appointment_id <> conflicting_appointment_id)
);

create index if not exists ludia_naver_sync_conflicts_open_idx
  on public.ludia_naver_sync_conflicts(salon_id, detected_at desc)
  where resolved_at is null;

alter table public.ludia_naver_sync_conflicts enable row level security;
revoke all on table public.ludia_naver_sync_conflicts from anon, authenticated;
create policy ludia_naver_sync_conflicts_no_client_access
on public.ludia_naver_sync_conflicts for all to anon, authenticated
using (false) with check (false);

-- Replaces the bridge projection RPC with the same signature/return type so api/naver-sync.js
-- remains backward compatible. Existing duration, manual customer links and enrichment survive.
create or replace function public.ludia_sync_naver_booking_to_appointment(
  p_salon_id uuid,
  p_external_id text,
  p_booking_no text,
  p_booking_date text,
  p_booking_time text,
  p_phone text,
  p_status text,
  p_raw_text text
) returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
  v_start timestamptz;
  v_end timestamptz;
  v_status text;
  v_label text;
  v_current public.ludia_appointments%rowtype;
  v_conflict uuid;
begin
  if p_salon_id is null or nullif(trim(p_external_id),'') is null then
    raise exception 'salon_id and external_id are required';
  end if;
  if p_booking_date is null or p_booking_time is null then return null; end if;

  begin
    v_start := ((p_booking_date::date + p_booking_time::time) at time zone 'Asia/Seoul');
  exception when others then
    return null;
  end;

  v_status := case p_status
    when 'cancelled' then 'cancelled'
    when 'completed' then 'completed'
    when 'no_show' then 'no_show'
    when 'requested' then 'pending'
    else 'confirmed'
  end;
  v_label := case when nullif(regexp_replace(coalesce(p_phone,''),'\D','','g'),'') is not null
    then '네이버 예약 · ' || right(regexp_replace(p_phone,'\D','','g'),4)
    else '네이버 예약' end;

  select * into v_current
  from public.ludia_appointments
  where salon_id=p_salon_id and source='naver' and external_source_id=p_external_id
  limit 1 for update;

  if not found then
    insert into public.ludia_appointments(
      salon_id,source,external_source_id,customer_name_snapshot,customer_phone_snapshot,
      service_name_snapshot,starts_at,ends_at,status,price,memo,source_updated_at
    ) values (
      p_salon_id,'naver',p_external_id,v_label,nullif(p_phone,''),'네이버 예약',
      v_start,v_start+interval '90 minutes',v_status,0,
      case when p_booking_no is not null then '네이버 예약번호 '||p_booking_no else '' end,now()
    ) returning id into v_id;
    return v_id;
  end if;

  v_id := v_current.id;
  v_end := v_start + greatest(interval '5 minutes',v_current.ends_at-v_current.starts_at);

  -- Only guard active time moves with a known staff assignment. Cancellation/completion/no-show
  -- must still flow through even if the old slot overlaps something else.
  if v_current.staff_user_id is not null
     and v_status in ('pending','confirmed')
     and v_start is distinct from v_current.starts_at then
    select a.id into v_conflict
    from public.ludia_appointments a
    where a.salon_id=p_salon_id
      and a.id<>v_current.id
      and a.staff_user_id=v_current.staff_user_id
      and a.status not in ('cancelled','completed','no_show')
      and a.starts_at < v_end
      and a.ends_at > v_start
    order by a.starts_at
    limit 1;
  end if;

  if v_conflict is not null then
    -- De-duplicate repeated bridge polls for the same unresolved requested move.
    if not exists (
      select 1 from public.ludia_naver_sync_conflicts c
      where c.appointment_id=v_current.id
        and c.conflicting_appointment_id=v_conflict
        and c.requested_starts_at=v_start
        and c.requested_ends_at=v_end
        and c.resolved_at is null
    ) then
      insert into public.ludia_naver_sync_conflicts(
        salon_id,appointment_id,conflicting_appointment_id,external_id,
        requested_starts_at,requested_ends_at
      ) values (p_salon_id,v_current.id,v_conflict,p_external_id,v_start,v_end);
    end if;

    -- Preserve the LUDIA slot. Non-time metadata/status is still refreshed so the bridge does
    -- not become stale while the owner resolves the scheduling conflict.
    update public.ludia_appointments
    set customer_phone_snapshot=coalesce(nullif(p_phone,''),customer_phone_snapshot),
        customer_name_snapshot=case when customer_id is null then v_label else customer_name_snapshot end,
        status=v_status,
        memo=case when p_booking_no is not null then '네이버 예약번호 '||p_booking_no else memo end,
        source_updated_at=now()
    where id=v_current.id;
    return v_current.id;
  end if;

  update public.ludia_appointments
  set starts_at=v_start,
      ends_at=v_end,
      customer_phone_snapshot=coalesce(nullif(p_phone,''),customer_phone_snapshot),
      customer_name_snapshot=case when customer_id is null then v_label else customer_name_snapshot end,
      status=v_status,
      memo=case when p_booking_no is not null then '네이버 예약번호 '||p_booking_no else memo end,
      source_updated_at=now()
  where id=v_current.id;

  return v_current.id;
end;
$$;

revoke all on function public.ludia_sync_naver_booking_to_appointment(uuid,text,text,text,text,text,text,text) from public,anon,authenticated;
grant execute on function public.ludia_sync_naver_booking_to_appointment(uuid,text,text,text,text,text,text,text) to service_role;

-- Conflict details deliberately stay server-only for now. A later manager-facing API can expose
-- only customer-safe appointment labels/times and explicit resolution actions. Never expose Naver
-- cookies, browser storage, passwords, CAPTCHA data or raw SmartPlace session material.
