-- LUDIA NAIL · Naver SmartPlace bridge persistence · shared INBETWEEN project / ludia_* namespace
create table if not exists public.ludia_external_bookings (
  id bigint generated by default as identity primary key,
  salon_id uuid not null references public.ludia_salons(id) on delete cascade,
  source text not null check (source in ('NAVER')),
  external_id text not null,
  booking_no text,
  booking_date text,
  booking_time text,
  phone text,
  status text not null default 'unknown',
  raw_text text,
  last_synced_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  unique(salon_id, source, external_id)
);

create table if not exists public.ludia_booking_sync_events (
  id bigint generated by default as identity primary key,
  salon_id uuid not null references public.ludia_salons(id) on delete cascade,
  event_type text not null check (event_type in ('created','updated')),
  source text not null check (source in ('NAVER')),
  external_id text not null,
  booking_no text,
  booking_date text,
  booking_time text,
  phone text,
  status text not null default 'unknown',
  raw_text text,
  received_at timestamptz not null default now()
);

create table if not exists public.ludia_integration_connections (
  id bigint generated by default as identity primary key,
  salon_id uuid not null references public.ludia_salons(id) on delete cascade,
  provider text not null,
  display_name text not null,
  state text not null default 'setup_required',
  last_sync_at timestamptz,
  last_error text,
  metadata jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now(),
  unique(salon_id, provider)
);

create index if not exists ludia_external_bookings_date_idx on public.ludia_external_bookings(salon_id, booking_date, booking_time);
create index if not exists ludia_booking_sync_events_received_idx on public.ludia_booking_sync_events(salon_id, received_at desc);

alter table public.ludia_external_bookings enable row level security;
alter table public.ludia_booking_sync_events enable row level security;
alter table public.ludia_integration_connections enable row level security;

revoke all on table public.ludia_external_bookings, public.ludia_booking_sync_events, public.ludia_integration_connections from anon, authenticated;

create policy ludia_external_bookings_no_client_access on public.ludia_external_bookings for all to anon, authenticated using (false) with check (false);
create policy ludia_booking_sync_events_no_client_access on public.ludia_booking_sync_events for all to anon, authenticated using (false) with check (false);
create policy ludia_integration_connections_no_client_access on public.ludia_integration_connections for all to anon, authenticated using (false) with check (false);

-- Server-side Naver bridge must attach LUDIA_SALON_ID and use SUPABASE_SECRET_KEY.
-- Never store Naver password, browser profile, cookies, or storageState here.
