/* LUDIA NAIL · native membership management
 * Authenticated salon only. Sales/adjustments are delegated to atomic Supabase RPCs.
 */
(()=>{
'use strict';
let client=null,salonId=null,busy=false,view='active',data={memberships:[],products:[],customers:[],staff:[]};
const $=s=>document.querySelector(s),won=n=>`${Number(n||0).toLocaleString('ko-KR')}원`;
const menuButton=()=>[...document.querySelectorAll('.native-settings-group button')].find(b=>b.querySelector('b')?.textContent.trim()==='회원권')||null;
function ensureSheet(){if($('#membershipSheet'))return;document.body.insertAdjacentHTML('beforeend',`<div class="sheet membership-sheet" id="membershipSheet" aria-hidden="true"><div class="sheet-backdrop" data-close-membership></div><div class="sheet-card membership-card"><div class="sheet-handle"></div><button class="sheet-close" data-close-membership aria-label="닫기">×</button><div class="sheet-body membership-body"><div class="membership-head"><div><span class="mini-label">MEMBERSHIP</span><h2>회원권</h2><p id="membershipSummary">잔액 · 횟수 · 만료 · 사용이력</p></div><button class="membership-add" id="membershipAdd">＋ 판매</button></div><div class="membership-segment" id="membershipSegment"><button data-membership-view="active" class="active">사용중</button><button data-membership-view="history">전체</button></div><div id="membershipContent"><div class="membership-loading">회원권을 불러오는 중…</div></div></div></div></div>`);document.querySelectorAll('[data-close-membership]').forEach(x=>x.addEventListener('click',close));$('#membershipSegment').addEventListener('click',e=>{const b=e.target.closest('[data-membership-view]');if(!b)return;view=b.dataset.membershipView;document.querySelectorAll('[data-membership-view]').forEach(x=>x.classList.toggle('active',x===b));render()});$('#membershipAdd').addEventListener('click',openSale)}
async function getClient(){if(client)return client;const r=await fetch('/api/salon-config',{cache:'no-store'}),cfg=await r.json();if(!cfg?.configured||!window.supabase?.createClient)throw new Error('cloud_unavailable');client=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'ludia-salon-auth'}});return client}
async function resolveSalon(){if(salonId)return salonId;const c=await getClient(),{data:{session}}=await c.auth.getSession();if(!session?.user)throw new Error('login_required');const {data:m,error}=await c.from('ludia_salon_members').select('salon_id').eq('user_id',session.user.id).eq('is_active',true).limit(1);if(error)throw error;salonId=m?.[0]?.salon_id;if(!salonId)throw new Error('salon_required');return salonId}
const balance=m=>m.kind==='amount'?won(m.remaining_amount):`${Number(m.remaining_count||0)}회`;
const expiry=m=>m.expires_at?new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',year:'numeric',month:'numeric',day:'numeric'}).format(new Date(m.expires_at)):'기간 없음';
function statusLabel(s){return({active:'사용중',used:'소진',expired:'만료',cancelled:'취소'}[s]||s)}
async function load(){if(busy)return;busy=true;const box=$('#membershipContent');if(box)box.innerHTML='<div class="membership-loading">회원권을 불러오는 중…</div>';try{const c=await getClient(),sid=await resolveSalon();const [mq,pq,cq,sq]=await Promise.all([c.from('ludia_customer_memberships').select('id,customer_id,product_id,kind,name_snapshot,remaining_amount,remaining_count,starts_at,expires_at,status,created_at').eq('salon_id',sid).order('created_at',{ascending:false}),c.from('ludia_membership_products').select('id,name,kind,sale_price,credit_amount,credit_count,valid_days,is_active').eq('salon_id',sid).eq('is_active',true).order('created_at'),c.from('ludia_customers').select('id,name,phone').eq('salon_id',sid).order('name').limit(1000),c.from('ludia_salon_members').select('user_id,display_name,is_active').eq('salon_id',sid).eq('is_active',true)]);const err=[mq,pq,cq,sq].find(x=>x.error)?.error;if(err)throw err;data={memberships:mq.data||[],products:pq.data||[],customers:cq.data||[],staff:sq.data||[]};render()}catch(error){console.warn('[LUDIA membership]',error);box.innerHTML=`<div class="membership-error"><b>회원권을 불러오지 못했어요.</b><span>${error?.message?.includes('relation')||error?.message?.includes('function')?'membership SQL 적용 상태를 확인해 주세요.':'클라우드 로그인과 연결 상태를 확인해 주세요.'}</span><button id="membershipRetry">다시 시도</button></div>`;$('#membershipRetry')?.addEventListener('click',load)}finally{busy=false}}
function render(){const box=$('#membershipContent');if(!box)return;const cm=new Map(data.customers.map(x=>[x.id,x])),rows=view==='active'?data.memberships.filter(x=>x.status==='active'):data.memberships;const active=data.memberships.filter(x=>x.status==='active');$('#membershipSummary').textContent=`사용중 ${active.length}개 · 금액권 ${won(active.filter(x=>x.kind==='amount').reduce((a,x)=>a+Number(x.remaining_amount||0),0))}`;box.innerHTML=rows.length?`<div class="membership-list">${rows.map(m=>`<button class="membership-row" data-membership-id="${m.id}"><span class="membership-row-main"><b>${window.LudiaEscapeHTML(cm.get(m.customer_id)?.name||'고객')} · ${window.LudiaEscapeHTML(m.name_snapshot)}</b><small>${expiry(m)} · ${statusLabel(m.status)}</small></span><strong>${balance(m)}</strong><i>›</i></button>`).join('')}</div>`:'<div class="membership-empty"><b>표시할 회원권이 없어요.</b><span>판매 버튼에서 첫 회원권을 등록할 수 있어요.</span></div>';box.querySelectorAll('[data-membership-id]').forEach(b=>b.addEventListener('click',()=>openDetail(b.dataset.membershipId)))}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="membership-modal" id="membershipModal"><div class="membership-modal-backdrop" data-membership-modal-close></div><div class="membership-modal-card"><div class="sheet-handle"></div><div class="membership-modal-head"><h3>${window.LudiaEscapeHTML(title)}</h3><button data-membership-modal-close>×</button></div>${body}</div></div>`);document.querySelectorAll('[data-membership-modal-close]').forEach(x=>x.addEventListener('click',closeModal))}
function closeModal(){$('#membershipModal')?.remove()}
function openSale(){if(!data.products.length)return alert('먼저 회원권 상품을 등록해 주세요.');modal('회원권 판매',`<div class="membership-form"><label><span>고객</span><select id="membershipCustomer">${data.customers.map(x=>`<option value="${x.id}">${window.LudiaEscapeHTML(x.name)}${window.LudiaEscapeHTML(x.phone?' · '+x.phone:'')}</option>`).join('')}</select></label><label><span>상품</span><select id="membershipProduct">${data.products.map(x=>`<option value="${x.id}">${window.LudiaEscapeHTML(x.name)} · ${won(x.sale_price)}</option>`).join('')}</select></label><label><span>결제</span><select id="membershipMethod"><option value="card">카드</option><option value="cash">현금</option><option value="transfer">이체</option><option value="other">기타</option></select></label><label><span>담당자</span><select id="membershipStaff"><option value="">미지정</option>${data.staff.map(x=>`<option value="${x.user_id}">${window.LudiaEscapeHTML(x.display_name)}</option>`).join('')}</select></label><label><span>메모</span><input id="membershipMemo" placeholder="선택 입력"></label><button class="membership-primary" id="membershipSellConfirm">판매 완료</button></div>`);$('#membershipSellConfirm').addEventListener('click',sell)}
async function sell(){const btn=$('#membershipSellConfirm');if(btn.disabled)return;btn.disabled=true;btn.textContent='처리 중…';try{const c=await getClient();const {error}=await c.rpc('ludia_sell_membership',{p_salon_id:salonId,p_customer_id:$('#membershipCustomer').value,p_product_id:$('#membershipProduct').value,p_payment_method:$('#membershipMethod').value,p_staff_user_id:$('#membershipStaff').value||null,p_memo:$('#membershipMemo').value||''});if(error)throw error;closeModal();await load()}catch(error){alert(error.message||'회원권 판매에 실패했어요.');btn.disabled=false;btn.textContent='판매 완료'}}
async function openDetail(id){const m=data.memberships.find(x=>x.id===id);if(!m)return;const c=await getClient(),{data:ledger,error}=await c.from('ludia_membership_ledger').select('id,delta_amount,delta_count,reason,created_at').eq('membership_id',id).order('created_at',{ascending:false}).limit(50);if(error)return alert(error.message);modal(m.name_snapshot,`<div class="membership-detail"><div class="membership-balance"><span>현재 잔여</span><strong>${balance(m)}</strong><small>${expiry(m)} · ${statusLabel(m.status)}</small></div><h4>사용 이력</h4><div class="membership-ledger">${ledger?.length?ledger.map(x=>`<div><span><b>${window.LudiaEscapeHTML(x.reason)}</b><small>${new Date(x.created_at).toLocaleDateString('ko-KR')}</small></span><strong>${m.kind==='amount'?`${Number(x.delta_amount||0)>0?'+':''}${Number(x.delta_amount||0).toLocaleString('ko-KR')}원`:`${Number(x.delta_count||0)>0?'+':''}${Number(x.delta_count||0)}회`}</strong></div>`).join(''):'<p>아직 사용 이력이 없어요.</p>'}</div>${m.status==='active'?`<button class="membership-secondary" id="membershipAdjust">잔액 조정</button>`:''}</div>`);$('#membershipAdjust')?.addEventListener('click',()=>openAdjust(m))}
function openAdjust(m){closeModal();modal('잔액 조정',`<div class="membership-form"><p class="membership-form-note">오입력 정정 등 관리자 조정용입니다. 실제 시술 사용은 결제에서 자동 차감됩니다.</p><label><span>${m.kind==='amount'?'금액 증감':'횟수 증감'}</span><input id="membershipDelta" type="number" step="${m.kind==='amount'?1000:1}" placeholder="예: ${m.kind==='amount'?'-10000':'-1'}"></label><label><span>사유</span><input id="membershipReason" placeholder="필수 입력"></label><button class="membership-primary" id="membershipAdjustConfirm">조정 적용</button></div>`);$('#membershipAdjustConfirm').addEventListener('click',async()=>{const delta=Number($('#membershipDelta').value),reason=$('#membershipReason').value.trim();if(!delta||!reason)return alert('증감값과 사유를 입력해 주세요.');try{const c=await getClient(),args={p_salon_id:salonId,p_membership_id:m.id,p_delta_amount:m.kind==='amount'?delta:null,p_delta_count:m.kind==='count'?delta:null,p_reason:reason},{error}=await c.rpc('ludia_adjust_membership',args);if(error)throw error;closeModal();await load()}catch(error){alert(error.message||'조정에 실패했어요.')}})}
function open(){ensureSheet();const s=$('#membershipSheet');s.classList.add('open');s.setAttribute('aria-hidden','false');document.body.style.overflow='hidden';load()}
function close(){const s=$('#membershipSheet');if(!s)return;s.classList.remove('open');s.setAttribute('aria-hidden','true');document.body.style.overflow=''}
const small=menuButton()?.querySelector('small');if(small)small.textContent='잔액 · 만료 · 판매 · 사용이력';document.addEventListener('click',e=>{const b=e.target.closest('.native-settings-group button');if(!b||b.querySelector('b')?.textContent.trim()!=='회원권')return;e.preventDefault();open()});
})();

