/* LUDIA NAIL · staff operations UI */
(()=>{'use strict';
let client=null,salonId=null,role=null,busy=false,month=new Date(),data={staff:[],rules:[],off:[],summary:[]};
const $=s=>document.querySelector(s),won=n=>`${Number(n||0).toLocaleString('ko-KR')}원`,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const menu=()=>[...document.querySelectorAll('.native-settings-group button')].find(b=>b.querySelector('b')?.textContent.trim()==='직원');
async function cloud(){if(client)return client;const r=await fetch('/api/salon-config',{cache:'no-store'}),cfg=await r.json();if(!cfg?.configured||!window.supabase?.createClient)throw Error('cloud_unavailable');client=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'ludia-salon-auth'}});return client}
async function context(){if(salonId)return;const c=await cloud(),{data:{session}}=await c.auth.getSession();if(!session?.user)throw Error('login_required');const {data,error}=await c.from('ludia_salon_members').select('salon_id,role').eq('user_id',session.user.id).eq('is_active',true).limit(1);if(error)throw error;salonId=data?.[0]?.salon_id;role=data?.[0]?.role;if(!salonId)throw Error('salon_required')}
function ensure(){if($('#staffSheet'))return;document.body.insertAdjacentHTML('beforeend',`<div class="sheet staff-sheet" id="staffSheet" aria-hidden="true"><div class="sheet-backdrop" data-close-staff></div><div class="sheet-card staff-card"><div class="sheet-handle"></div><button class="sheet-close" data-close-staff>×</button><div class="sheet-body"><div class="staff-head"><div><span class="mini-label">TEAM</span><h2>직원</h2><p>근무 · 휴무 · 매출 · 예상급여</p></div><button id="staffAddOff">＋ 휴무</button></div><div class="staff-month"><button id="staffPrev">‹</button><b id="staffMonth"></b><button id="staffNext">›</button></div><div id="staffContent"><div class="staff-loading">직원 현황을 불러오는 중…</div></div></div></div></div>`);document.querySelectorAll('[data-close-staff]').forEach(x=>x.onclick=close);$('#staffPrev').onclick=()=>shift(-1);$('#staffNext').onclick=()=>shift(1);$('#staffAddOff').onclick=openOff}
function shift(n){month=new Date(month.getFullYear(),month.getMonth()+n,1);load()}
async function load(){if(busy)return;busy=true;try{await context();const c=await cloud(),first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,1);const [sq,rq,oq,mq]=await Promise.all([c.from('ludia_salon_members').select('user_id,display_name,role,is_active').eq('salon_id',salonId).eq('is_active',true).order('created_at'),c.from('ludia_staff_work_rules').select('*').eq('salon_id',salonId),c.from('ludia_staff_time_off').select('*').eq('salon_id',salonId).lt('starts_at',last.toISOString()).gt('ends_at',first.toISOString()).order('starts_at'),c.rpc('ludia_staff_month_summary',{p_salon_id:salonId,p_month:`${first.getFullYear()}-${String(first.getMonth()+1).padStart(2,'0')}-01`})]);const err=[sq,rq,oq,mq].find(x=>x.error)?.error;if(err)throw err;data={staff:sq.data||[],rules:rq.data||[],off:oq.data||[],summary:mq.data?.staff||[]};render()}catch(e){console.warn('[LUDIA staff]',e);$('#staffContent').innerHTML=`<div class="staff-error"><b>직원 운영 데이터를 불러오지 못했어요.</b><span>${/relation|function/i.test(e.message)?'staff_operations.sql 적용이 필요해요.':'클라우드 로그인 상태를 확인해 주세요.'}</span><button id="staffRetry">다시 시도</button></div>`;$('#staffRetry').onclick=load}finally{busy=false}}
function render(){const sm=new Map(data.summary.map(x=>[x.user_id,x]));$('#staffMonth').textContent=new Intl.DateTimeFormat('ko-KR',{year:'numeric',month:'long'}).format(month);$('#staffAddOff').hidden=!['owner','manager'].includes(role);$('#staffContent').innerHTML=`<div class="staff-list">${data.staff.map(s=>{const x=sm.get(s.user_id)||{},off=data.off.filter(o=>o.staff_user_id===s.user_id);return `<button class="staff-row" data-staff="${s.user_id}"><span class="staff-avatar">${esc(s.display_name).slice(0,1)}</span><span class="staff-copy"><b>${esc(s.display_name)}</b><small>${s.role==='owner'?'원장':s.role==='manager'?'매니저':'직원'} · 완료 ${x.completed||0}건${off.length?` · 휴무 ${off.length}`:''}</small></span><span class="staff-money"><b>${won(x.sales)}</b><small>예상 ${won(x.estimated_pay)}</small></span><i>›</i></button>`}).join('')}</div>`;document.querySelectorAll('[data-staff]').forEach(b=>b.onclick=()=>detail(b.dataset.staff))}
function modal(title,body){document.body.insertAdjacentHTML('beforeend',`<div class="staff-modal" id="staffModal"><div class="staff-modal-backdrop" data-staff-modal-close></div><div class="staff-modal-card"><div class="sheet-handle"></div><div class="staff-modal-head"><h3>${esc(title)}</h3><button data-staff-modal-close>×</button></div>${body}</div></div>`);document.querySelectorAll('[data-staff-modal-close]').forEach(x=>x.onclick=()=>$('#staffModal')?.remove())}
function detail(id){const s=data.staff.find(x=>x.user_id===id),x=data.summary.find(x=>x.user_id===id)||{},rules=data.rules.filter(x=>x.staff_user_id===id),days=['일','월','화','수','목','금','토'];modal(s.display_name,`<div class="staff-detail"><div class="staff-kpis"><div><span>매출</span><b>${won(x.sales)}</b></div><div><span>완료</span><b>${x.completed||0}건</b></div><div><span>인센티브</span><b>${won(x.commission)}</b></div><div><span>예상급여</span><b>${won(x.estimated_pay)}</b></div></div><h4>기본 근무</h4><div class="staff-rules">${days.map((d,i)=>{const r=rules.find(x=>x.weekday===i);return `<div><b>${d}</b><span>${!r?'미설정':r.is_working?`${String(r.starts_at).slice(0,5)}–${String(r.ends_at).slice(0,5)}`:'휴무'}</span></div>`}).join('')}</div>${['owner','manager'].includes(role)?`<button class="staff-secondary" id="staffEditPay">급여 기준 설정</button>`:''}</div>`);$('#staffEditPay')?.addEventListener('click',()=>pay(s,x))}
function pay(s,x){$('#staffModal')?.remove();modal(`${s.display_name} 급여 기준`,`<div class="staff-form"><label><span>월 기본급</span><input id="staffBase" type="number" step="10000" value="${Number(x.base_pay||0)}"></label><label><span>매출 인센티브 %</span><input id="staffRate" type="number" min="0" max="100" step="0.1" value="${Number(x.commission_rate||0)}"></label><button class="staff-primary" id="staffPaySave">저장</button></div>`);$('#staffPaySave').onclick=async()=>{try{const c=await cloud(),{error}=await c.from('ludia_staff_pay_profiles').upsert({salon_id:salonId,staff_user_id:s.user_id,base_monthly_pay:Number($('#staffBase').value||0),sales_commission_rate:Number($('#staffRate').value||0)},{onConflict:'salon_id,staff_user_id'});if(error)throw error;$('#staffModal')?.remove();await load()}catch(e){alert(e.message)}}}
function openOff(){if(!data.staff.length)return;modal('휴무 등록',`<div class="staff-form"><label><span>직원</span><select id="staffOffWho">${data.staff.map(s=>`<option value="${s.user_id}">${esc(s.display_name)}</option>`).join('')}</select></label><label><span>시작</span><input id="staffOffStart" type="datetime-local"></label><label><span>종료</span><input id="staffOffEnd" type="datetime-local"></label><label><span>구분</span><select id="staffOffKind"><option value="off">휴무</option><option value="vacation">휴가</option><option value="sick">병가</option><option value="other">기타</option></select></label><label><span>메모</span><input id="staffOffNote"></label><button class="staff-primary" id="staffOffSave">등록</button></div>`);$('#staffOffSave').onclick=async()=>{const a=$('#staffOffStart').value,b=$('#staffOffEnd').value;if(!a||!b||new Date(b)<=new Date(a))return alert('휴무 시간을 확인해 주세요.');try{const c=await cloud(),{error}=await c.from('ludia_staff_time_off').insert({salon_id:salonId,staff_user_id:$('#staffOffWho').value,starts_at:new Date(a).toISOString(),ends_at:new Date(b).toISOString(),kind:$('#staffOffKind').value,note:$('#staffOffNote').value||''});if(error)throw error;$('#staffModal')?.remove();await load()}catch(e){alert(e.message)}}}
function open(){ensure();$('#staffSheet').classList.add('open');$('#staffSheet').setAttribute('aria-hidden','false');document.body.style.overflow='hidden';load()}
function close(){$('#staffSheet')?.classList.remove('open');$('#staffSheet')?.setAttribute('aria-hidden','true');document.body.style.overflow=''}
const small=menu()?.querySelector('small');if(small)small.textContent='근무 · 휴무 · 매출 · 예상급여';document.addEventListener('click',e=>{const b=e.target.closest('.native-settings-group button');if(!b||b.querySelector('b')?.textContent.trim()!=='직원')return;e.preventDefault();open()});
})();
