/* LUDIA NAIL · staff today operations view */
(()=>{'use strict';
let client=null,salonId=null,busy=false,active=false;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=t=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t));
const labels={pending:'예정',confirmed:'예정',arrived:'도착',in_service:'시술중',completed:'완료',no_show:'노쇼'};
async function cloud(){if(client)return client;const r=await fetch('/api/salon-config',{cache:'no-store'}),cfg=await r.json();if(!cfg?.configured||!window.supabase?.createClient)throw Error('cloud_unavailable');client=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'ludia-salon-auth'}});return client}
async function context(){if(salonId)return;const c=await cloud(),{data:{session}}=await c.auth.getSession();if(!session?.user)throw Error('login_required');const {data,error}=await c.from('ludia_salon_members').select('salon_id').eq('user_id',session.user.id).eq('is_active',true).limit(1);if(error)throw error;salonId=data?.[0]?.salon_id;if(!salonId)throw Error('salon_required')}
function mount(){const sheet=$('#staffSheet'),head=sheet?.querySelector('.staff-head');if(!sheet||!head||$('#staffMode'))return false;head.insertAdjacentHTML('afterend','<div class="staff-mode" id="staffMode"><button data-staff-mode="today">오늘 운영</button><button class="active" data-staff-mode="month">월간</button></div><section class="staff-day hidden" id="staffDay"></section>');sheet.querySelectorAll('[data-staff-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.staffMode));return true}
function switchMode(mode){active=mode==='today';$('#staffMode')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.staffMode===mode));$('#staffDay')?.classList.toggle('hidden',!active);$('#staffContent')?.classList.toggle('hidden',active);$('#staffSheet .staff-month')?.classList.toggle('hidden',active);$('#staffAddOff')?.classList.toggle('hidden',active);if(active)load()}
function status(a){if(a.needs_checkout)return['결제 대기','checkout'];if(a.is_overrun)return['시간 초과','overrun'];if(a.is_late)return['미도착','late'];return[labels[a.status]||a.status,a.status]}
function render(d){const c=d.counts||{},staff=d.staff||[];$('#staffDay').innerHTML=`<div class="staff-day-summary"><div><b>${c.in_service||0}</b><span>시술중</span></div><div><b>${c.waiting||0}</b><span>도착</span></div><div><b>${c.checkout||0}</b><span>결제대기</span></div><div><b>${c.late||0}</b><span>미도착</span></div></div><div class="staff-day-list">${staff.map(s=>`<article class="staff-day-person"><header><span class="staff-avatar">${esc(s.name).slice(0,1)}</span><div><b>${esc(s.name)}</b><small>${(s.appointments||[]).length}건</small></div></header>${(s.appointments||[]).length?`<div class="staff-day-appts">${s.appointments.map(a=>{const st=status(a);return `<div class="staff-day-appt"><time>${fmt(a.starts_at)}<small>${fmt(a.ends_at)}</small></time><span class="staff-day-line"></span><div class="staff-day-copy"><b>${esc(a.customer_name||'고객')}</b><small>${esc(a.service_name||'시술')}${a.source==='naver'?' · 네이버':''}</small></div><em class="${esc(st[1])}">${esc(st[0])}</em></div>`}).join('')}</div>`:'<p class="staff-day-empty">오늘 예약 없음</p>'}</article>`).join('')}</div>`}
async function load(){if(busy||!active)return;busy=true;$('#staffDay').innerHTML='<div class="staff-loading">오늘 운영 현황을 불러오는 중…</div>';try{await context();const c=await cloud(),{data,error}=await c.rpc('ludia_staff_day_board',{p_salon_id:salonId,p_day:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date())});if(error)throw error;render(data||{})}catch(e){console.warn('[LUDIA staff day]',e);$('#staffDay').innerHTML=`<div class="staff-error"><b>오늘 운영 현황을 불러오지 못했어요.</b><span>${/function/i.test(e.message)?'staff_day_board.sql 적용이 필요해요.':'클라우드 연결을 확인해 주세요.'}</span><button id="staffDayRetry">다시 시도</button></div>`;$('#staffDayRetry')?.addEventListener('click',load)}finally{busy=false}}
const obs=new MutationObserver(()=>{if(mount())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{const b=e.target.closest('.native-settings-group button');if(b?.querySelector('b')?.textContent.trim()==='직원')setTimeout(()=>{mount();switchMode('today')},0)});
})();
