/* LUDIA NAIL · staff today operations view */
(()=>{'use strict';
let client=null,salonId=null,busy=false,active=false,actionBusy=false;const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=t=>new Intl.DateTimeFormat('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(t));const labels={pending:'예정',confirmed:'예정',arrived:'도착',in_service:'시술중',completed:'완료',no_show:'노쇼'};
async function cloud(){if(client)return client;const r=await fetch('/api/salon-config',{cache:'no-store'}),cfg=await r.json();if(!cfg?.configured||!window.supabase?.createClient)throw Error('cloud_unavailable');client=window.supabase.createClient(cfg.url,cfg.anonKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false,storageKey:'ludia-salon-auth'}});return client}
async function context(){if(salonId)return;const c=await cloud(),{data:{session}}=await c.auth.getSession();if(!session?.user)throw Error('login_required');const {data,error}=await c.from('ludia_salon_members').select('salon_id').eq('user_id',session.user.id).eq('is_active',true).limit(1);if(error)throw error;salonId=data?.[0]?.salon_id;if(!salonId)throw Error('salon_required')}
function mount(){const sheet=$('#staffSheet'),head=sheet?.querySelector('.staff-head');if(!sheet||!head||$('#staffMode'))return false;head.insertAdjacentHTML('afterend','<div class="staff-mode" id="staffMode"><button data-staff-mode="today">오늘 운영</button><button class="active" data-staff-mode="month">월간</button></div><section class="staff-day hidden" id="staffDay"></section>');sheet.querySelectorAll('[data-staff-mode]').forEach(b=>b.onclick=()=>switchMode(b.dataset.staffMode));$('#staffDay').addEventListener('click',handleAction);return true}
function switchMode(mode){active=mode==='today';$('#staffMode')?.querySelectorAll('button').forEach(b=>b.classList.toggle('active',b.dataset.staffMode===mode));$('#staffDay')?.classList.toggle('hidden',!active);$('#staffContent')?.classList.toggle('hidden',active);$('#staffSheet .staff-month')?.classList.toggle('hidden',active);$('#staffAddOff')?.classList.toggle('hidden',active);if(active)load()}
function status(a){if(a.needs_checkout)return['결제 대기','checkout'];if(a.is_overrun)return['시간 초과','overrun'];if(a.is_late)return['미도착','late'];return[labels[a.status]||a.status,a.status]}
function action(a){if(a.needs_checkout||a.status==='in_service')return['checkout','결제'];if(a.status==='arrived')return['in_service','시술 시작'];if(['pending','confirmed'].includes(a.status))return['arrived','도착'];return null}
function canNoShow(a){return !!a.is_late&&['pending','confirmed'].includes(a.status)}
function render(d){const c=d.counts||{},staff=d.staff||[];$('#staffDay').innerHTML=`<div class="staff-day-summary"><div><b>${c.in_service||0}</b><span>시술중</span></div><div><b>${c.waiting||0}</b><span>도착</span></div><div><b>${c.checkout||0}</b><span>결제대기</span></div><div><b>${c.late||0}</b><span>미도착</span></div></div><div class="staff-day-list">${staff.map(s=>`<article class="staff-day-person"><header><span class="staff-avatar">${esc(s.name).slice(0,1)}</span><div><b>${esc(s.name)}</b><small>${(s.appointments||[]).length}건</small></div></header>${(s.appointments||[]).length?`<div class="staff-day-appts">${s.appointments.map(a=>{const st=status(a),ac=action(a),payload=encodeURIComponent(JSON.stringify({...a,staff_name:s.name}));return `<div class="staff-day-appt"><time>${fmt(a.starts_at)}<small>${fmt(a.ends_at)}</small></time><span class="staff-day-line"></span><div class="staff-day-copy"><b>${esc(a.customer_name||'고객')}</b><small>${esc(a.service_name||'시술')}${a.source==='naver'?' · 네이버':''}</small></div><div class="staff-day-tail"><em class="${esc(st[1])}">${esc(st[0])}</em><div class="staff-day-actions">${canNoShow(a)?`<button class="staff-day-more" data-floor-action="no_show" data-appt="${payload}" aria-label="노쇼 처리">•••</button>`:''}${ac?`<button class="staff-day-action" data-floor-action="${ac[0]}" data-appt="${payload}">${ac[1]}</button>`:''}</div></div></div>`}).join('')}</div>`:'<p class="staff-day-empty">오늘 예약 없음</p>'}</article>`).join('')}</div>`}
function confirmNoShow(a){return new Promise(resolve=>{const wrap=document.createElement('div');wrap.className='staff-confirm-wrap';wrap.innerHTML=`<button class="staff-confirm-backdrop" aria-label="닫기"></button><section class="staff-confirm" role="dialog" aria-modal="true" aria-label="노쇼 처리 확인"><span class="staff-confirm-grab"></span><h3>노쇼로 처리할까요?</h3><p><b>${esc(a.customer_name||'고객')}</b> · ${fmt(a.starts_at)} 예약</p><small>노쇼 처리 후에는 오늘 운영 화면에서 종료 상태로 표시됩니다.</small><div><button data-confirm="cancel">취소</button><button class="danger" data-confirm="ok">노쇼 처리</button></div></section>`;document.body.appendChild(wrap);const done=v=>{wrap.remove();resolve(v)};wrap.querySelector('.staff-confirm-backdrop').onclick=()=>done(false);wrap.querySelector('[data-confirm="cancel"]').onclick=()=>done(false);wrap.querySelector('[data-confirm="ok"]').onclick=()=>done(true)})}
async function transition(a,next,b){actionBusy=true;b.disabled=true;const original=b.textContent;b.textContent='저장 중…';try{await context();const c=await cloud(),{error}=await c.rpc('ludia_transition_appointment',{p_salon_id:salonId,p_appointment_id:a.id,p_next_status:next});if(error)throw error;await window.LudiaSalonCloud?.refresh?.();await load(true)}catch(err){console.error('[LUDIA floor action]',err);alert(/function|transition/i.test(err.message||'')?'appointment_transition.sql 적용이 필요해요.':'상태를 변경하지 못했어요. 다시 확인해 주세요.')}finally{actionBusy=false;b.disabled=false;b.textContent=original}}
async function handleAction(e){const b=e.target.closest('[data-floor-action]');if(!b||actionBusy)return;let a;try{a=JSON.parse(decodeURIComponent(b.dataset.appt))}catch{return}const next=b.dataset.floorAction;if(next==='checkout'){const checkout=window.LudiaCheckout;if(!checkout?.open)return alert('결제 화면을 준비하지 못했어요.');return checkout.open({cloudId:a.id,customer:a.customer_name||'고객',service:a.service_name||'시술',staff:a.staff_name||'미지정',time:fmt(a.starts_at),amount:a.price||0,status:a.status})}if(next==='no_show'&&!(await confirmNoShow(a)))return;await transition(a,next,b)}
async function load(force=false){if((busy&&!force)||!active)return;busy=true;$('#staffDay').innerHTML='<div class="staff-loading">오늘 운영 현황을 불러오는 중…</div>';try{await context();const c=await cloud(),{data,error}=await c.rpc('ludia_staff_day_board',{p_salon_id:salonId,p_day:new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul'}).format(new Date())});if(error)throw error;render(data||{})}catch(e){console.warn('[LUDIA staff day]',e);$('#staffDay').innerHTML=`<div class="staff-error"><b>오늘 운영 현황을 불러오지 못했어요.</b><span>${/function/i.test(e.message)?'staff_day_board.sql 적용이 필요해요.':'클라우드 연결을 확인해 주세요.'}</span><button id="staffDayRetry">다시 시도</button></div>`;$('#staffDayRetry')?.addEventListener('click',()=>load(true))}finally{busy=false}}
const obs=new MutationObserver(()=>{if(mount())obs.disconnect()});obs.observe(document.body,{childList:true,subtree:true});document.addEventListener('click',e=>{const b=e.target.closest('.native-settings-group button');if(b?.querySelector('b')?.textContent.trim()==='직원')setTimeout(()=>{mount();switchMode('today')},0)});
})();
