const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),vm=require('node:vm');
const M=require('../booking-model.js'),root=path.resolve(__dirname,'..');
const settings={open:'11:00',close:'21:00',step:30},base={settings,date:new Date(2026,9,6,12),staff:'원장',time:'14:00',duration:60,dayOffset:0};
test('capacity is per staff, completed occupies time, cancelled/no-show free it; adjacent allowed',()=>{for(const status of ['대기','진행중','완료','completed']){const appointments=[{staff:'원장',time:'14:00',duration:60,status}];assert.equal(M.availability({...base,appointments}).available,false);assert.equal(M.availability({...base,staff:'직원',appointments}).available,true);assert.equal(M.availability({...base,time:'15:00',appointments}).available,true)}for(const status of ['취소','노쇼','cancelled','no_show'])assert.equal(M.availability({...base,appointments:[{staff:'원장',time:'14:00',duration:60,status}]}).available,true)});
test('weekday hours and holiday override apply through treatment end',()=>{const s={...settings,weekly:{1:{closed:true},0:{open:'12:00',close:'18:00'}},exceptions:[{date:'2026-10-06',closed:true}]};assert.equal(M.availability({...base,settings:s}).reason,'time_off');assert.equal(M.dayHours(s,new Date(2026,9,5)).closed,true);assert.equal(M.availability({...base,settings:s,date:new Date(2026,9,11),time:'17:30'}).reason,'outside_work_hours')});
test('malformed time, unassigned staff, and invalid duration cannot be booked',()=>{for(const time of ['25:00','11:60','x',''])assert.equal(M.availability({...base,time}).available,false);for(const duration of [0,4,721,NaN])assert.equal(M.availability({...base,duration}).available,false);assert.equal(M.availability({...base,staff:'미지정'}).available,false)});
test('overlap groups include different starts and preserve full-width reading, adjacency separates',()=>{const g=M.groups([{time:'14:00',duration:60},{time:'14:30',duration:90},{time:'16:00',duration:30}]);assert.deepEqual(g.map(x=>[x.start,x.end,x.items.length]),[[840,960,2],[960,990,1]])});
const row=(status='확정')=>({text:'김씨 젤 아트 원장',fields:{bookingNo:'N123',date:'2026.10.06',time:'오후 2:30',phone:'010-1234-5678',status}});
test('bridge accepts verified fields only; rejects guessed text and impossible date/time/status',async()=>{const R=await import('../bridge/booking-reader.js');assert.equal(R.parseCandidate({text:'N123 2026-10-06 14:30 확정'}),null);assert.equal(R.parseCandidate(row()).time,'14:30');assert.equal(R.parseCandidate({...row(),fields:{...row().fields,date:'2026.02.30'}}),null);assert.equal(R.parseCandidate({...row(),fields:{...row().fields,time:'24:00'}}),null);assert.equal(R.parseCandidate(row('알 수 없음')),null);assert.equal(R.parseCandidate(row()).service,undefined);assert.deepEqual(R.parseCandidate(row()).attachments,[])});
test('bridge retries are stable; A-B-A and new PC installation have distinct event keys; absence never cancels',async()=>{const R=await import('../bridge/booking-reader.js'),s={bridgeId:'pc1',bookings:{}},a=R.buildChanges([row()],s);assert.equal(a.events[0].eventId,R.buildChanges([row()],s).events[0].eventId);const ack={...s,bookings:a.next};assert.equal(R.buildChanges([row()],ack).events.length,0);const b=R.buildChanges([row('취소')],ack),c=R.buildChanges([row()],{...ack,bookings:b.next});assert.notEqual(c.events[0].eventId,a.events[0].eventId);assert.notEqual(R.buildChanges([row()],{bridgeId:'pc2',bookings:{}}).events[0].eventId,a.events[0].eventId);assert.equal(R.buildChanges([],ack).events.length,0);assert.equal(R.buildChanges([row(),row('취소')],s).rejectedCount,1);assert.equal(R.buildChanges([row(),row()],s).events.length,1)});
function appContext(){const element={classList:{toggle(){},add(){},remove(){},contains(){return false}},style:{},dataset:{},addEventListener(){},setAttribute(){},value:'',innerHTML:'',textContent:''};const c=vm.createContext({console,Date,structuredClone,setTimeout,clearTimeout,window:{},document:{querySelector:()=>element,querySelectorAll:()=>[],documentElement:{dataset:{}},body:element},localStorage:{getItem:()=>null},navigator:{}}),s=fs.readFileSync(path.join(root,'app.js'),'utf8');vm.runInContext(fs.readFileSync(path.join(root,'booking-model.js'),'utf8'),c);vm.runInContext(s.slice(0,s.indexOf("$$('[data-nav]').forEach")),c);return{c,s}}
test('grid geometry uses actual duration and fractional start for 15/30/60 minute settings',()=>{const {c}=appContext();for(const step of [15,30,60]){c.step=step;const r=JSON.parse(vm.runInContext(`salonAppointments=[];state.bookingHours={open:'11:00',close:'21:00',step};JSON.stringify(bookingAppointmentSpan({time:'14:10',duration:45}))`,c));assert.equal(r.pos,190/step);assert.equal(r.length,45/step)}});
test('48-reference classifier still uses 6 golden/12 style/30 board refs and 5-view nearest matcher',()=>{const {c,s}=appContext(),data=JSON.parse(fs.readFileSync(path.join(root,'data/nail-reference-features.json')));assert.deepEqual([data.goldenPricingRefs.length,data.ludiaStyleRefs.length,data.sampleBoardRefs.length],[6,12,30]);vm.runInContext(s.slice(s.indexOf('const PRICING_VISUAL_REFS_FALLBACK='),s.indexOf('async function localPricePhotoDraft(')),c);c.refs=[...data.goldenPricingRefs.map(x=>({...x,qualityWeight:1.35})),...data.ludiaStyleRefs,...data.sampleBoardRefs];c.golden=data.goldenPricingRefs;const results=JSON.parse(vm.runInContext(`pricingVisualScaleCache=pricingVisualScales(refs);JSON.stringify(golden.map(g=>{const hit=ensemblePricingVisualRefs(Array.from({length:5},()=>g.f),refs)[0];return[hit.ref.id,pricingRefAmount(hit.ref),hit.votes]}))`,c));assert.deepEqual(results,[['G01',50000,5],['G02',80000,5],['G03',57000,5],['G04',88000,5],['G05',92000,5],['G06',90000,5]])});
const sid='11111111-1111-4111-8111-111111111111';
async function apiFixture(fn){const names=['SUPABASE_URL','SUPABASE_SECRET_KEY','SUPABASE_SERVICE_ROLE_KEY','LUDIA_SALON_ID','LUDIA_SYNC_TOKEN','LUDIA_INTEGRATION_ADMIN_TOKEN'],saved=names.map(n=>process.env[n]),fetch=global.fetch;Object.assign(process.env,{SUPABASE_URL:'https://example.invalid',SUPABASE_SECRET_KEY:'server-key',LUDIA_SALON_ID:sid,LUDIA_SYNC_TOKEN:'s'.repeat(48),LUDIA_INTEGRATION_ADMIN_TOKEN:'a'.repeat(48)});try{await fn()}finally{names.forEach((n,i)=>saved[i]===undefined?delete process.env[n]:process.env[n]=saved[i]);global.fetch=fetch}}
const response=(data,status=200)=>({ok:status<400,status,json:async()=>data});
async function invoke(handler,req){const res={code:200,status(n){this.code=n;return this},setHeader(){return this},end(body){this.body=JSON.parse(body);return this}};await handler({headers:{},...req},res);return res}
test('health never pretends connected without salon, confirmed parser, and recent successful sync',async()=>{await apiFixture(async()=>{const {default:handler,staleState}=await import('../api/naver-status.js');assert.equal(staleState({state:'connected',last_sync_at:new Date().toISOString()}).state,'selector_required');assert.equal(staleState({state:'connected',last_sync_at:new Date(Date.now()-700000).toISOString(),metadata:{diagnostics:{parser_verified:true}}}).state,'stale');global.fetch=async()=>response([]);const r=await invoke(handler,{method:'GET'});assert.equal(r.body.configured,false);assert.equal(r.body.state,'setup_required');assert.equal(r.body.lastSyncAt,null)})});
test('external admin requires a distinct long key and cannot expand salon scope',async()=>{await apiFixture(async()=>{const {resolveAccess}=await import('../server/naver-access.mjs');const auth={'x-ludia-integration-token':'a'.repeat(48)};assert.equal((await resolveAccess({headers:auth,query:{salonId:'other'}},{})).salonId,sid);assert.equal(await resolveAccess({headers:{'x-ludia-integration-token':'s'.repeat(48)}},{}),null);process.env.LUDIA_INTEGRATION_ADMIN_TOKEN=process.env.LUDIA_SYNC_TOKEN;assert.equal(await resolveAccess({headers:{'x-ludia-integration-token':'s'.repeat(48)}},{}),null)})});
test('sync refuses unverified events and DB failure never acknowledges; login heartbeat does not update last_sync_at',async()=>{await apiFixture(async()=>{const {default:handler}=await import('../api/naver-sync.js'),R=await import('../bridge/booking-reader.js'),event=R.buildChanges([row()],{bridgeId:'pc',bookings:{}}).events[0],headers={authorization:'Bearer '+'s'.repeat(48)};let r=await invoke(handler,{method:'POST',headers,body:{source:'NAVER',events:[event]}});assert.equal(r.code,409);global.fetch=async url=>response(url.includes('ludia_salons')?[{id:sid}]:{},url.includes('/rpc/')?500:200);r=await invoke(handler,{method:'POST',headers,body:{source:'NAVER',events:[event],bridgeState:'connected',diagnostics:{parserVerified:true}}});assert.equal(r.code,502);assert.equal(r.body.persisted,undefined);let connection;global.fetch=async(url,opts)=>{if(url.includes('ludia_salons'))return response([{id:sid}]);connection=JSON.parse(opts.body)[0];return response(null,204)};r=await invoke(handler,{method:'POST',headers,body:{source:'NAVER',events:[],bridgeState:'login_required'}});assert.equal(r.body.persisted,true);assert.equal(connection.last_sync_at,undefined);assert.equal(connection.state,'login_required')})});
test('scoped conflict resolver ignores caller salon and posts the fixed scope',async()=>{await apiFixture(async()=>{const {default:handler}=await import('../api/naver-conflict.js');let body;global.fetch=async(url,opts)=>{if(url.includes('ludia_salons'))return response([{id:sid}]);body=JSON.parse(opts.body);return response({resolved:true})};const r=await invoke(handler,{method:'POST',headers:{'x-ludia-integration-token':'a'.repeat(48)},body:{conflictId:7,action:'accept_naver',salonId:'other'}});assert.equal(r.code,200);assert.equal(body.p_salon_id,sid);assert.equal(body.p_conflict_id,7)})});
test('scoped calendar enforces authentication and at most 14 real dates',async()=>{await apiFixture(async()=>{const {default:handler,validRange}=await import('../api/naver-appointments.js');assert.equal(validRange('2026-02-30','2026-03-02'),false);assert.equal(validRange('2026-10-01','2026-10-20'),false);assert.equal(validRange('2026-10-01','2026-10-08'),true);assert.equal((await invoke(handler,{method:'GET',query:{from:'2026-10-01',to:'2026-10-08'}})).code,401)})});

test('durable outbox preserves A-B-A after server commit but failed acknowledgment or PC restart',async()=>{const R=await import('../bridge/booking-reader.js');let state={bridgeId:'pc1',bookings:{}};state=R.commitPending(R.stageChanges([row()],state,{parserVerified:true}).state);const staged=R.stageChanges([row('취소')],state,{parserVerified:true}).state,restarted=JSON.parse(JSON.stringify(staged));assert.equal(restarted.pending.events[0].eventId,staged.pending.events[0].eventId);assert.throws(()=>R.stageChanges([row()],restarted,{}),/pending_batch_not_acknowledged/);state=R.commitPending(restarted);const reversal=R.stageChanges([row()],state,{parserVerified:true});assert.equal(reversal.changes.events.length,1);assert.equal(reversal.changes.events[0].type,'updated');assert.notEqual(reversal.changes.events[0].eventId,staged.pending.events[0].eventId);assert.equal(reversal.state.pending.events[0].booking.status,'confirmed');assert.equal(R.commitPending(reversal.state).pending,undefined)});
